import type { AppProps } from "next/app";

import "@/styles/globals.scss";
import Layout from "@/layout/Layout";
import Head from "next/head";
import { getLayoutInfo } from "@/services/getLayoutInfo";

export default function App({ Component, pageProps }: AppProps) {
  const layoutInfo = getLayoutInfo();
  return (
    <>
      <Head>
        <title>ASA hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/favicon-32.png" sizes="32x32" />
        <link rel="icon" href="/assets/images/favicon-192.png" sizes="192x192" />
        <link rel="apple-touch-icon" href="/assets/images/apple-touch-favicon.png" />
        <link rel="dns-prefetch" href="//fonts.googleapis.com"></link>
      </Head>
      <Layout layoutInfo={layoutInfo}>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
